### 1. importando a biblioteca 

Por convenção, importamos o Numpy utilizando o alias np.

In [3]:
%pip install numpy 

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print(f"Versão do NumPy: {np.__version__}")

Versão do NumPy: 2.4.2


### 2. Criando Arrays (Vetores e Matrizes)

A principal estrutura de dados do NumPy é o ndarray.


In [4]:
# Criando um array ID (Vetor) a partir de uma lista Pyton
vetor = np.array([1, 2, 3, 4, 5])
print("Vetor ID: ", vetor)

# Criando um array 2D (Matriz) a partir de uma lista de listas
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatriz 2D:\n", matriz)

Vetor ID:  [1 2 3 4 5]

Matriz 2D:
 [[1 2 3]
 [4 5 6]]


### Funções úteis para criação de Arrays

O numpy possui funções nativas para gerar arrays comuns rapidamente, o que é muito útil para inicializar pesos em Redes Neurais, por exemplo.

In [6]:
# Arrays de zeros
zeros = np.zeros((2, 3)) # 2 linhas, 3 colunas
print("Zeros\n", zeros)

Zeros
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Array de uns
uns = np.ones((3, 3))
print("\nUns:\n", uns)


Uns:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Array com uma sequência de números (simular ao range() do Python)
sequencia = np.arange(0, 10, 2) # Inicio, Fim (exclusivo), Passo
print("\nSequência (arange):", sequencia)


Sequência (arange): [0 2 4 6 8]


In [9]:
# Valores literalmente espaçados
espacados = np.linspace(0, 1, 5) # 5 valores entre 0 e 1
print("\nLinspace", espacados)


Linspace [0.   0.25 0.5  0.75 1.  ]


### 3. Inspecionando Arrays

É crucial saber o tamanho  e o formato dos seus dados, especialmente ao preparar datsets para mineração de dados.

In [12]:
print("Formato (shape): ", matriz.shape) # Linhas, colunas
print("Dimensões (ndim): ", matriz.ndim) # Números de dimensões
print("Tamanho Total (size): ", matriz.size) # Total de elementos 
print("Tipo de dado (dtype): ", matriz.dtype) # Tipo de elementos (ex: int64, int32, int8) 

Formato (shape):  (2, 3)
Dimensões (ndim):  2
Tamanho Total (size):  6
Tipo de dado (dtype):  int64


### 4. Operações Matematicas Básicas

O NumPy permite fazer operações elemento a elemento de forma direta, sem a necessidade de loops for (conceito conhecido como vetorização).

In [13]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("Soma: ", a + b)
print("Subtração: ", b - a)
print("Multiplicação: ", a * b)
print("Divisão: ", a / b)

Soma:  [11 22 33]
Subtração:  [ 9 18 27]
Multiplicação:  [10 40 90]
Divisão:  [0.1 0.1 0.1]


In [15]:
# Funções estáticas básicas

dados = np.array([15, 20, 25, 30, 35])
print("\nMédia: ", np.mean(dados))
print("Desvio Padrão ", np.std(dados))
print("Valor Máximo: ", np.max(dados))


Média:  25.0
Desvio Padrão  7.0710678118654755
Valor Máximo:  35


### 5. Indexação e Fatiamento (Slicing)

Você pode acessar elementos específicos ou extrair subconjuntos do array.

In [16]:
arr = np.array([10, 20, 30, 40, 50])

print("Primeiro elemento: ", arr[0])
print("Último elemento: ", arr[-1])
print("Fatiamento (índice 1 ao 3): ", arr[1:4]) # O indice final é exclusivo

Primeiro elemento:  10
Último elemento:  50
Fatiamento (índice 1 ao 3):  [20 30 40]


In [17]:
# Em matrizes 2D

matriz_ex = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nMatriz completa: \n", matriz_ex)
print("\nElemento na linha 1, coluna 2: ", matriz_ex[1, 2])
print("Todas as linhas, apenas a coluna 1: \n", matriz_ex[:, 1])


Matriz completa: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Elemento na linha 1, coluna 2:  60
Todas as linhas, apenas a coluna 1: 
 [20 50 80]
